shadow_box: Shadow Box {
  style.shadow: true
  style.fill: "#dbeafe"
}

multi_box: Multiple {
  style.multiple: true
  style.fill: "#dcfce7"
}

three_d_box: 3D Box {
  style.3d: true
  style.fill: "#fef3c7"
}

shadow_box -> multi_box -> three_d_box
